// Configuración github
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Estudio y aplicación de modelos predictivos a partir del análisis de datos educativos en plataformas de teleformación
Ignacio Albors Fernández <ignacio.albors@gmail.com>
v1.0
:numbered:
:toc: macro
:toclevels: 5
:lang: es
:encoding: utf8
:sectnumlevels: 5
:toc-title: Índice
:toc-placement: manual
:stem: latexmath
// stem needed by asciimath, latextmath
:icons: font
:experimental:
:imagesdir: _images
:table-caption: Tabla
:example-caption: Ejemplo
:included:

// Notas:
// Habría que hablar del constructivismo, construccionismo. De la teoría
// psicológica que hay detrás de Moodle. Incorporar notas de cuaderno rojo.

:numbered!:

== Resumen

La aplicación de las técnicas de Data Mining a los entornos educativos se conoce como Educational Data Mining (o EDM).
Es un área de estudio relativamente reciente cuyo origen temporal puede fijarse, aproximadamente, alrededor de 2005.
Es, por lo tanto, una disciplina con mucho margen para la exploración y experimentación.

EDM viene de la mano de los cambios que ha traído la revolución digital como la posibilidad casi ilimitada de generar y almacenar información de entornos educativos en formatos digitales que permiten su tratamiento y comunicación de forma mucho más rápida y sencilla que lo que era habitual hasta entonces.

También como consecuencia de esa revolución se ha producido un interés creciente en los entornos educativos virtuales (VLE por sus siglas en inglés, Virtual Learning Environments).
Esto puede verse, por ejemplo, en la proliferación de cursos en línea masivos y abiertos (MOOCs) o en el empleo cada vez más extendido de plataformas software orientadas a la educación.
Una de las plataformas más extendida e importante en este campo es Moodle.

En este proyecto se va a elaborar un estudio de un modelo predictivo, a partir de técnicas de Data Mining que generen reglas de asociación a partir de un conjunto de datos obtenidos en un entorno Moodle.


== Palabras clave
Educational Data Mining, Association Rule Mining, algoritmos, Weka, Moodle, Learning Management System, Entorno Virtual de Aprendizaje, algoritmo Apriori.

toc::[]

<<<

== Abstract
The application of Data Mining techniques in an educational environments is known as Educational Data Mining (or EDM).
It is a relatively recent area of ​​study whose origin can be set, approximately, around 2005.
It is, therefore, a discipline with a lot of room for exploration and experimentation.

EDM comes hand in hand with the changes that the digital revolution has brought like almost unlimited power of generating and storing information from educational environments in digital formats that allow their treatment and communication much faster and easier than what was usual until then.

Also as a consequence of that revolution there has been a growing interest in
Virtual Learning Environments (VLE). This can be seen, for example, in the proliferation of massive open online courses (MOOC) or in the increasingly widespread use of software platforms with an educational orientation. One of the most widespread and important platforms in this field is Moodle.

In this project a study of a predictive model will be elaborated, starting from
Data Mining techniques that generate association rules from a set of
data obtained in a Moodle environment.

== Keywords
Educational Data Mining, Association Rule Mining, algorithms, Weka, Moodle, Learning Management System, Virtual Learning Environment, Apriori algorithm.
